// <auto-generated />
using AnimalApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalApi.Migrations
{
    [DbContext(typeof(AnimalApiContext))]
    [Migration("20220401202207_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            Breed = "shorthair",
                            Name = "chihiro",
                            Sex = "female",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 6,
                            Breed = "american bulldog",
                            Name = "ira",
                            Sex = "male",
                            Species = "dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 3,
                            Breed = "longhair",
                            Name = "perchik",
                            Sex = "male",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 2,
                            Breed = "shorthair",
                            Name = "mika",
                            Sex = "female",
                            Species = "cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            Breed = "shorthair",
                            Name = "hodel",
                            Sex = "female",
                            Species = "cat"
                        });
                });

            modelBuilder.Entity("AnimalApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "ParkOne",
                            State = "OR"
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "ParkTwo",
                            State = "NY"
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "ParkThree",
                            State = "OR"
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "ParkFour",
                            State = "NC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
